name = "Compromise"
uuid = "254bc946-86ae-484f-a9da-8147cb79ba93"
authors = ["Manuel Berkemeier <manuelbb@mail.uni-paderborn.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
